//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Global_Chat.GC_WebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GC_WebService.GC_ServiceSoap")]
    public interface GC_ServiceSoap {
        
        // CODEGEN: Generating message contract since element name Odaları_ListeleResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Odaları_Listele", ReplyAction="*")]
        Global_Chat.GC_WebService.Odaları_ListeleResponse Odaları_Listele(Global_Chat.GC_WebService.Odaları_ListeleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Odaları_Listele", ReplyAction="*")]
        System.Threading.Tasks.Task<Global_Chat.GC_WebService.Odaları_ListeleResponse> Odaları_ListeleAsync(Global_Chat.GC_WebService.Odaları_ListeleRequest request);
        
        // CODEGEN: Generating message contract since element name Odadaki_Kişileri_ListeleResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Odadaki_Kişileri_Listele", ReplyAction="*")]
        Global_Chat.GC_WebService.Odadaki_Kişileri_ListeleResponse Odadaki_Kişileri_Listele(Global_Chat.GC_WebService.Odadaki_Kişileri_ListeleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Odadaki_Kişileri_Listele", ReplyAction="*")]
        System.Threading.Tasks.Task<Global_Chat.GC_WebService.Odadaki_Kişileri_ListeleResponse> Odadaki_Kişileri_ListeleAsync(Global_Chat.GC_WebService.Odadaki_Kişileri_ListeleRequest request);
        
        // CODEGEN: Generating message contract since element name Odadaki_Mesajları_ListeleResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Odadaki_Mesajları_Listele", ReplyAction="*")]
        Global_Chat.GC_WebService.Odadaki_Mesajları_ListeleResponse Odadaki_Mesajları_Listele(Global_Chat.GC_WebService.Odadaki_Mesajları_ListeleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Odadaki_Mesajları_Listele", ReplyAction="*")]
        System.Threading.Tasks.Task<Global_Chat.GC_WebService.Odadaki_Mesajları_ListeleResponse> Odadaki_Mesajları_ListeleAsync(Global_Chat.GC_WebService.Odadaki_Mesajları_ListeleRequest request);
        
        // CODEGEN: Generating message contract since element name kullanıcı_adi from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Kullanıcı_Kontrol", ReplyAction="*")]
        Global_Chat.GC_WebService.Kullanıcı_KontrolResponse Kullanıcı_Kontrol(Global_Chat.GC_WebService.Kullanıcı_KontrolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Kullanıcı_Kontrol", ReplyAction="*")]
        System.Threading.Tasks.Task<Global_Chat.GC_WebService.Kullanıcı_KontrolResponse> Kullanıcı_KontrolAsync(Global_Chat.GC_WebService.Kullanıcı_KontrolRequest request);
        
        // CODEGEN: Generating message contract since element name kullanıcı_adi from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Kullanıcı_Ekle", ReplyAction="*")]
        Global_Chat.GC_WebService.Kullanıcı_EkleResponse Kullanıcı_Ekle(Global_Chat.GC_WebService.Kullanıcı_EkleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Kullanıcı_Ekle", ReplyAction="*")]
        System.Threading.Tasks.Task<Global_Chat.GC_WebService.Kullanıcı_EkleResponse> Kullanıcı_EkleAsync(Global_Chat.GC_WebService.Kullanıcı_EkleRequest request);
        
        // CODEGEN: Generating message contract since element name k_adi from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mesaj_Ekle", ReplyAction="*")]
        Global_Chat.GC_WebService.Mesaj_EkleResponse Mesaj_Ekle(Global_Chat.GC_WebService.Mesaj_EkleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mesaj_Ekle", ReplyAction="*")]
        System.Threading.Tasks.Task<Global_Chat.GC_WebService.Mesaj_EkleResponse> Mesaj_EkleAsync(Global_Chat.GC_WebService.Mesaj_EkleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Odaları_ListeleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Odaları_Listele", Namespace="http://tempuri.org/", Order=0)]
        public Global_Chat.GC_WebService.Odaları_ListeleRequestBody Body;
        
        public Odaları_ListeleRequest() {
        }
        
        public Odaları_ListeleRequest(Global_Chat.GC_WebService.Odaları_ListeleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Odaları_ListeleRequestBody {
        
        public Odaları_ListeleRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Odaları_ListeleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Odaları_ListeleResponse", Namespace="http://tempuri.org/", Order=0)]
        public Global_Chat.GC_WebService.Odaları_ListeleResponseBody Body;
        
        public Odaları_ListeleResponse() {
        }
        
        public Odaları_ListeleResponse(Global_Chat.GC_WebService.Odaları_ListeleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Odaları_ListeleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Odaları_ListeleResult;
        
        public Odaları_ListeleResponseBody() {
        }
        
        public Odaları_ListeleResponseBody(string Odaları_ListeleResult) {
            this.Odaları_ListeleResult = Odaları_ListeleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Odadaki_Kişileri_ListeleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Odadaki_Kişileri_Listele", Namespace="http://tempuri.org/", Order=0)]
        public Global_Chat.GC_WebService.Odadaki_Kişileri_ListeleRequestBody Body;
        
        public Odadaki_Kişileri_ListeleRequest() {
        }
        
        public Odadaki_Kişileri_ListeleRequest(Global_Chat.GC_WebService.Odadaki_Kişileri_ListeleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Odadaki_Kişileri_ListeleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Oda_Id;
        
        public Odadaki_Kişileri_ListeleRequestBody() {
        }
        
        public Odadaki_Kişileri_ListeleRequestBody(int Oda_Id) {
            this.Oda_Id = Oda_Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Odadaki_Kişileri_ListeleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Odadaki_Kişileri_ListeleResponse", Namespace="http://tempuri.org/", Order=0)]
        public Global_Chat.GC_WebService.Odadaki_Kişileri_ListeleResponseBody Body;
        
        public Odadaki_Kişileri_ListeleResponse() {
        }
        
        public Odadaki_Kişileri_ListeleResponse(Global_Chat.GC_WebService.Odadaki_Kişileri_ListeleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Odadaki_Kişileri_ListeleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Odadaki_Kişileri_ListeleResult;
        
        public Odadaki_Kişileri_ListeleResponseBody() {
        }
        
        public Odadaki_Kişileri_ListeleResponseBody(string Odadaki_Kişileri_ListeleResult) {
            this.Odadaki_Kişileri_ListeleResult = Odadaki_Kişileri_ListeleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Odadaki_Mesajları_ListeleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Odadaki_Mesajları_Listele", Namespace="http://tempuri.org/", Order=0)]
        public Global_Chat.GC_WebService.Odadaki_Mesajları_ListeleRequestBody Body;
        
        public Odadaki_Mesajları_ListeleRequest() {
        }
        
        public Odadaki_Mesajları_ListeleRequest(Global_Chat.GC_WebService.Odadaki_Mesajları_ListeleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Odadaki_Mesajları_ListeleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Oda_Id;
        
        public Odadaki_Mesajları_ListeleRequestBody() {
        }
        
        public Odadaki_Mesajları_ListeleRequestBody(int Oda_Id) {
            this.Oda_Id = Oda_Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Odadaki_Mesajları_ListeleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Odadaki_Mesajları_ListeleResponse", Namespace="http://tempuri.org/", Order=0)]
        public Global_Chat.GC_WebService.Odadaki_Mesajları_ListeleResponseBody Body;
        
        public Odadaki_Mesajları_ListeleResponse() {
        }
        
        public Odadaki_Mesajları_ListeleResponse(Global_Chat.GC_WebService.Odadaki_Mesajları_ListeleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Odadaki_Mesajları_ListeleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Odadaki_Mesajları_ListeleResult;
        
        public Odadaki_Mesajları_ListeleResponseBody() {
        }
        
        public Odadaki_Mesajları_ListeleResponseBody(string Odadaki_Mesajları_ListeleResult) {
            this.Odadaki_Mesajları_ListeleResult = Odadaki_Mesajları_ListeleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Kullanıcı_KontrolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Kullanıcı_Kontrol", Namespace="http://tempuri.org/", Order=0)]
        public Global_Chat.GC_WebService.Kullanıcı_KontrolRequestBody Body;
        
        public Kullanıcı_KontrolRequest() {
        }
        
        public Kullanıcı_KontrolRequest(Global_Chat.GC_WebService.Kullanıcı_KontrolRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Kullanıcı_KontrolRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string kullanıcı_adi;
        
        public Kullanıcı_KontrolRequestBody() {
        }
        
        public Kullanıcı_KontrolRequestBody(string kullanıcı_adi) {
            this.kullanıcı_adi = kullanıcı_adi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Kullanıcı_KontrolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Kullanıcı_KontrolResponse", Namespace="http://tempuri.org/", Order=0)]
        public Global_Chat.GC_WebService.Kullanıcı_KontrolResponseBody Body;
        
        public Kullanıcı_KontrolResponse() {
        }
        
        public Kullanıcı_KontrolResponse(Global_Chat.GC_WebService.Kullanıcı_KontrolResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Kullanıcı_KontrolResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Kullanıcı_KontrolResult;
        
        public Kullanıcı_KontrolResponseBody() {
        }
        
        public Kullanıcı_KontrolResponseBody(string Kullanıcı_KontrolResult) {
            this.Kullanıcı_KontrolResult = Kullanıcı_KontrolResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Kullanıcı_EkleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Kullanıcı_Ekle", Namespace="http://tempuri.org/", Order=0)]
        public Global_Chat.GC_WebService.Kullanıcı_EkleRequestBody Body;
        
        public Kullanıcı_EkleRequest() {
        }
        
        public Kullanıcı_EkleRequest(Global_Chat.GC_WebService.Kullanıcı_EkleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Kullanıcı_EkleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int oda_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string kullanıcı_adi;
        
        public Kullanıcı_EkleRequestBody() {
        }
        
        public Kullanıcı_EkleRequestBody(int oda_id, string kullanıcı_adi) {
            this.oda_id = oda_id;
            this.kullanıcı_adi = kullanıcı_adi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Kullanıcı_EkleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Kullanıcı_EkleResponse", Namespace="http://tempuri.org/", Order=0)]
        public Global_Chat.GC_WebService.Kullanıcı_EkleResponseBody Body;
        
        public Kullanıcı_EkleResponse() {
        }
        
        public Kullanıcı_EkleResponse(Global_Chat.GC_WebService.Kullanıcı_EkleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Kullanıcı_EkleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Kullanıcı_EkleResult;
        
        public Kullanıcı_EkleResponseBody() {
        }
        
        public Kullanıcı_EkleResponseBody(string Kullanıcı_EkleResult) {
            this.Kullanıcı_EkleResult = Kullanıcı_EkleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Mesaj_EkleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Mesaj_Ekle", Namespace="http://tempuri.org/", Order=0)]
        public Global_Chat.GC_WebService.Mesaj_EkleRequestBody Body;
        
        public Mesaj_EkleRequest() {
        }
        
        public Mesaj_EkleRequest(Global_Chat.GC_WebService.Mesaj_EkleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Mesaj_EkleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int oda_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int k_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string k_adi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string msj;
        
        public Mesaj_EkleRequestBody() {
        }
        
        public Mesaj_EkleRequestBody(int oda_id, int k_id, string k_adi, string msj) {
            this.oda_id = oda_id;
            this.k_id = k_id;
            this.k_adi = k_adi;
            this.msj = msj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Mesaj_EkleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Mesaj_EkleResponse", Namespace="http://tempuri.org/", Order=0)]
        public Global_Chat.GC_WebService.Mesaj_EkleResponseBody Body;
        
        public Mesaj_EkleResponse() {
        }
        
        public Mesaj_EkleResponse(Global_Chat.GC_WebService.Mesaj_EkleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Mesaj_EkleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Mesaj_EkleResult;
        
        public Mesaj_EkleResponseBody() {
        }
        
        public Mesaj_EkleResponseBody(string Mesaj_EkleResult) {
            this.Mesaj_EkleResult = Mesaj_EkleResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GC_ServiceSoapChannel : Global_Chat.GC_WebService.GC_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GC_ServiceSoapClient : System.ServiceModel.ClientBase<Global_Chat.GC_WebService.GC_ServiceSoap>, Global_Chat.GC_WebService.GC_ServiceSoap {
        
        public GC_ServiceSoapClient() {
        }
        
        public GC_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GC_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GC_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GC_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Global_Chat.GC_WebService.Odaları_ListeleResponse Global_Chat.GC_WebService.GC_ServiceSoap.Odaları_Listele(Global_Chat.GC_WebService.Odaları_ListeleRequest request) {
            return base.Channel.Odaları_Listele(request);
        }
        
        public string Odaları_Listele() {
            Global_Chat.GC_WebService.Odaları_ListeleRequest inValue = new Global_Chat.GC_WebService.Odaları_ListeleRequest();
            inValue.Body = new Global_Chat.GC_WebService.Odaları_ListeleRequestBody();
            Global_Chat.GC_WebService.Odaları_ListeleResponse retVal = ((Global_Chat.GC_WebService.GC_ServiceSoap)(this)).Odaları_Listele(inValue);
            return retVal.Body.Odaları_ListeleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Global_Chat.GC_WebService.Odaları_ListeleResponse> Global_Chat.GC_WebService.GC_ServiceSoap.Odaları_ListeleAsync(Global_Chat.GC_WebService.Odaları_ListeleRequest request) {
            return base.Channel.Odaları_ListeleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Global_Chat.GC_WebService.Odaları_ListeleResponse> Odaları_ListeleAsync() {
            Global_Chat.GC_WebService.Odaları_ListeleRequest inValue = new Global_Chat.GC_WebService.Odaları_ListeleRequest();
            inValue.Body = new Global_Chat.GC_WebService.Odaları_ListeleRequestBody();
            return ((Global_Chat.GC_WebService.GC_ServiceSoap)(this)).Odaları_ListeleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Global_Chat.GC_WebService.Odadaki_Kişileri_ListeleResponse Global_Chat.GC_WebService.GC_ServiceSoap.Odadaki_Kişileri_Listele(Global_Chat.GC_WebService.Odadaki_Kişileri_ListeleRequest request) {
            return base.Channel.Odadaki_Kişileri_Listele(request);
        }
        
        public string Odadaki_Kişileri_Listele(int Oda_Id) {
            Global_Chat.GC_WebService.Odadaki_Kişileri_ListeleRequest inValue = new Global_Chat.GC_WebService.Odadaki_Kişileri_ListeleRequest();
            inValue.Body = new Global_Chat.GC_WebService.Odadaki_Kişileri_ListeleRequestBody();
            inValue.Body.Oda_Id = Oda_Id;
            Global_Chat.GC_WebService.Odadaki_Kişileri_ListeleResponse retVal = ((Global_Chat.GC_WebService.GC_ServiceSoap)(this)).Odadaki_Kişileri_Listele(inValue);
            return retVal.Body.Odadaki_Kişileri_ListeleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Global_Chat.GC_WebService.Odadaki_Kişileri_ListeleResponse> Global_Chat.GC_WebService.GC_ServiceSoap.Odadaki_Kişileri_ListeleAsync(Global_Chat.GC_WebService.Odadaki_Kişileri_ListeleRequest request) {
            return base.Channel.Odadaki_Kişileri_ListeleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Global_Chat.GC_WebService.Odadaki_Kişileri_ListeleResponse> Odadaki_Kişileri_ListeleAsync(int Oda_Id) {
            Global_Chat.GC_WebService.Odadaki_Kişileri_ListeleRequest inValue = new Global_Chat.GC_WebService.Odadaki_Kişileri_ListeleRequest();
            inValue.Body = new Global_Chat.GC_WebService.Odadaki_Kişileri_ListeleRequestBody();
            inValue.Body.Oda_Id = Oda_Id;
            return ((Global_Chat.GC_WebService.GC_ServiceSoap)(this)).Odadaki_Kişileri_ListeleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Global_Chat.GC_WebService.Odadaki_Mesajları_ListeleResponse Global_Chat.GC_WebService.GC_ServiceSoap.Odadaki_Mesajları_Listele(Global_Chat.GC_WebService.Odadaki_Mesajları_ListeleRequest request) {
            return base.Channel.Odadaki_Mesajları_Listele(request);
        }
        
        public string Odadaki_Mesajları_Listele(int Oda_Id) {
            Global_Chat.GC_WebService.Odadaki_Mesajları_ListeleRequest inValue = new Global_Chat.GC_WebService.Odadaki_Mesajları_ListeleRequest();
            inValue.Body = new Global_Chat.GC_WebService.Odadaki_Mesajları_ListeleRequestBody();
            inValue.Body.Oda_Id = Oda_Id;
            Global_Chat.GC_WebService.Odadaki_Mesajları_ListeleResponse retVal = ((Global_Chat.GC_WebService.GC_ServiceSoap)(this)).Odadaki_Mesajları_Listele(inValue);
            return retVal.Body.Odadaki_Mesajları_ListeleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Global_Chat.GC_WebService.Odadaki_Mesajları_ListeleResponse> Global_Chat.GC_WebService.GC_ServiceSoap.Odadaki_Mesajları_ListeleAsync(Global_Chat.GC_WebService.Odadaki_Mesajları_ListeleRequest request) {
            return base.Channel.Odadaki_Mesajları_ListeleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Global_Chat.GC_WebService.Odadaki_Mesajları_ListeleResponse> Odadaki_Mesajları_ListeleAsync(int Oda_Id) {
            Global_Chat.GC_WebService.Odadaki_Mesajları_ListeleRequest inValue = new Global_Chat.GC_WebService.Odadaki_Mesajları_ListeleRequest();
            inValue.Body = new Global_Chat.GC_WebService.Odadaki_Mesajları_ListeleRequestBody();
            inValue.Body.Oda_Id = Oda_Id;
            return ((Global_Chat.GC_WebService.GC_ServiceSoap)(this)).Odadaki_Mesajları_ListeleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Global_Chat.GC_WebService.Kullanıcı_KontrolResponse Global_Chat.GC_WebService.GC_ServiceSoap.Kullanıcı_Kontrol(Global_Chat.GC_WebService.Kullanıcı_KontrolRequest request) {
            return base.Channel.Kullanıcı_Kontrol(request);
        }
        
        public string Kullanıcı_Kontrol(string kullanıcı_adi) {
            Global_Chat.GC_WebService.Kullanıcı_KontrolRequest inValue = new Global_Chat.GC_WebService.Kullanıcı_KontrolRequest();
            inValue.Body = new Global_Chat.GC_WebService.Kullanıcı_KontrolRequestBody();
            inValue.Body.kullanıcı_adi = kullanıcı_adi;
            Global_Chat.GC_WebService.Kullanıcı_KontrolResponse retVal = ((Global_Chat.GC_WebService.GC_ServiceSoap)(this)).Kullanıcı_Kontrol(inValue);
            return retVal.Body.Kullanıcı_KontrolResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Global_Chat.GC_WebService.Kullanıcı_KontrolResponse> Global_Chat.GC_WebService.GC_ServiceSoap.Kullanıcı_KontrolAsync(Global_Chat.GC_WebService.Kullanıcı_KontrolRequest request) {
            return base.Channel.Kullanıcı_KontrolAsync(request);
        }
        
        public System.Threading.Tasks.Task<Global_Chat.GC_WebService.Kullanıcı_KontrolResponse> Kullanıcı_KontrolAsync(string kullanıcı_adi) {
            Global_Chat.GC_WebService.Kullanıcı_KontrolRequest inValue = new Global_Chat.GC_WebService.Kullanıcı_KontrolRequest();
            inValue.Body = new Global_Chat.GC_WebService.Kullanıcı_KontrolRequestBody();
            inValue.Body.kullanıcı_adi = kullanıcı_adi;
            return ((Global_Chat.GC_WebService.GC_ServiceSoap)(this)).Kullanıcı_KontrolAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Global_Chat.GC_WebService.Kullanıcı_EkleResponse Global_Chat.GC_WebService.GC_ServiceSoap.Kullanıcı_Ekle(Global_Chat.GC_WebService.Kullanıcı_EkleRequest request) {
            return base.Channel.Kullanıcı_Ekle(request);
        }
        
        public string Kullanıcı_Ekle(int oda_id, string kullanıcı_adi) {
            Global_Chat.GC_WebService.Kullanıcı_EkleRequest inValue = new Global_Chat.GC_WebService.Kullanıcı_EkleRequest();
            inValue.Body = new Global_Chat.GC_WebService.Kullanıcı_EkleRequestBody();
            inValue.Body.oda_id = oda_id;
            inValue.Body.kullanıcı_adi = kullanıcı_adi;
            Global_Chat.GC_WebService.Kullanıcı_EkleResponse retVal = ((Global_Chat.GC_WebService.GC_ServiceSoap)(this)).Kullanıcı_Ekle(inValue);
            return retVal.Body.Kullanıcı_EkleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Global_Chat.GC_WebService.Kullanıcı_EkleResponse> Global_Chat.GC_WebService.GC_ServiceSoap.Kullanıcı_EkleAsync(Global_Chat.GC_WebService.Kullanıcı_EkleRequest request) {
            return base.Channel.Kullanıcı_EkleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Global_Chat.GC_WebService.Kullanıcı_EkleResponse> Kullanıcı_EkleAsync(int oda_id, string kullanıcı_adi) {
            Global_Chat.GC_WebService.Kullanıcı_EkleRequest inValue = new Global_Chat.GC_WebService.Kullanıcı_EkleRequest();
            inValue.Body = new Global_Chat.GC_WebService.Kullanıcı_EkleRequestBody();
            inValue.Body.oda_id = oda_id;
            inValue.Body.kullanıcı_adi = kullanıcı_adi;
            return ((Global_Chat.GC_WebService.GC_ServiceSoap)(this)).Kullanıcı_EkleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Global_Chat.GC_WebService.Mesaj_EkleResponse Global_Chat.GC_WebService.GC_ServiceSoap.Mesaj_Ekle(Global_Chat.GC_WebService.Mesaj_EkleRequest request) {
            return base.Channel.Mesaj_Ekle(request);
        }
        
        public string Mesaj_Ekle(int oda_id, int k_id, string k_adi, string msj) {
            Global_Chat.GC_WebService.Mesaj_EkleRequest inValue = new Global_Chat.GC_WebService.Mesaj_EkleRequest();
            inValue.Body = new Global_Chat.GC_WebService.Mesaj_EkleRequestBody();
            inValue.Body.oda_id = oda_id;
            inValue.Body.k_id = k_id;
            inValue.Body.k_adi = k_adi;
            inValue.Body.msj = msj;
            Global_Chat.GC_WebService.Mesaj_EkleResponse retVal = ((Global_Chat.GC_WebService.GC_ServiceSoap)(this)).Mesaj_Ekle(inValue);
            return retVal.Body.Mesaj_EkleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Global_Chat.GC_WebService.Mesaj_EkleResponse> Global_Chat.GC_WebService.GC_ServiceSoap.Mesaj_EkleAsync(Global_Chat.GC_WebService.Mesaj_EkleRequest request) {
            return base.Channel.Mesaj_EkleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Global_Chat.GC_WebService.Mesaj_EkleResponse> Mesaj_EkleAsync(int oda_id, int k_id, string k_adi, string msj) {
            Global_Chat.GC_WebService.Mesaj_EkleRequest inValue = new Global_Chat.GC_WebService.Mesaj_EkleRequest();
            inValue.Body = new Global_Chat.GC_WebService.Mesaj_EkleRequestBody();
            inValue.Body.oda_id = oda_id;
            inValue.Body.k_id = k_id;
            inValue.Body.k_adi = k_adi;
            inValue.Body.msj = msj;
            return ((Global_Chat.GC_WebService.GC_ServiceSoap)(this)).Mesaj_EkleAsync(inValue);
        }
    }
}
